### ISSUE TITLE
Integration tests are failing

### ISSUE THREAD

**Issue by Ferenc-** [ruby-shoryuken/shoryuken#768]
Running the test SQS server either as 
`podman run --pod=moto-sqs-server-pod --rm quay.io/cjlarose/moto-sqs-server:1.1.0`
or 
`podman run --pod=moto-sqs-server-pod --rm quay.io/cjlarose/moto-sqs-server:1.0.0`

and  running the integrations tests as such:

` podman run  -i --rm --pod=moto-sqs-server-pod -v ${PWD}:${PWD}:z --workdir=${PWD} --entrypoint=bash docker.io/library/ruby:3.1.4 <<<$'bundle install && bundle exec rake spec:integration'`

fails with:

````
/usr/local/bin/ruby -I/usr/local/bundle/gems/rspec-core-3.13.0/lib:/usr/local/bundle/gems/rspec-support-3.13.1/lib /usr/local/bundle/gems/rspec-core-3.13.0/exe/rspec --pattern spec/integration/\*\*/\*_spec.rb
FFF

Failures:

  1) Shoryuken::Launcher Consuming messages consumes as a command worker
     Failure/Error: sleep 0.5

     Timeout::Error:
       execution expired
     # ./spec/integration/launcher_spec.rb:101:in `sleep'
     # ./spec/integration/launcher_spec.rb:101:in `block in poll_queues_until'
     # ./spec/integration/launcher_spec.rb:99:in `poll_queues_until'
     # ./spec/integration/launcher_spec.rb:66:in `block (3 levels) in <top (required)>'

  2) Shoryuken::Launcher Consuming messages consumes a message
     Failure/Error: sleep 0.5

     Timeout::Error:
       execution expired
     # ./spec/integration/launcher_spec.rb:101:in `sleep'
     # ./spec/integration/launcher_spec.rb:101:in `block in poll_queues_until'
     # ./spec/integration/launcher_spec.rb:99:in `poll_queues_until'
     # ./spec/integration/launcher_spec.rb:76:in `block (3 levels) in <top (required)>'

  3) Shoryuken::Launcher Consuming messages consumes a batch
     Failure/Error: client.send_message_batch(sanitize_messages!(options).merge(queue_url: url))

     Aws::SQS::Errors::EmptyBatchRequest:
       There should be at least one SendMessageBatchRequestEntry in the request.
     # /usr/local/bundle/gems/aws-sdk-core-3.196.1/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
     # /usr/local/bundle/gems/aws-sdk-core-3.196.1/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
     # /usr/local/bundle/gems/aws-sdk-core-3.196.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
     # /usr/local/bundle/gems/aws-sdk-core-3.196.1/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
     # /usr/local/bundle/gems/aws-sdk-core-3.196.1/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
     # /usr/local/bundle/gems/aws-sdk-core-3.196.1/lib/seahorse/client/plugins/request_callback.rb:89:in `call'
     # /usr/local/bundle/gems/aws-sdk-core-3.196.1/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
     # /usr/local/bundle/gems/aws-sdk-core-3.196.1/lib/seahorse/client/plugins/response_target.rb:24:in `call'
     # /usr/local/bundle/gems/aws-sdk-core-3.196.1/lib/seahorse/client/request.rb:72:in `send_request'
     # /usr/local/bundle/gems/aws-sdk-sqs-1.65.0/lib/aws-sdk-sqs/client.rb:2365:in `send_message_batch'
     # ./lib/shoryuken/queue.rb:43:in `send_messages'
     # ./spec/integration/launcher_spec.rb:86:in `block (3 levels) in <top (required)>'

Finished in 20.23 seconds (files took 0.5964 seconds to load)
3 examples, 3 failures

Failed examples:

rspec ./spec/integration/launcher_spec.rb:63 # Shoryuken::Launcher Consuming messages consumes as a command worker
rspec ./spec/integration/launcher_spec.rb:71 # Shoryuken::Launcher Consuming messages consumes a message
rspec ./spec/integration/launcher_spec.rb:81 # Shoryuken::Launcher Consuming messages consumes a batch

/usr/local/bin/ruby -I/usr/local/bundle/gems/rspec-core-3.13.0/lib:/usr/local/bundle/gems/rspec-support-3.13.1/lib /usr/local/bundle/gems/rspec-core-3.13.0/exe/rspec --pattern spec/integration/\*\*/\*_spec.rb failed
````

**Comment by Ferenc-** [comment]
Remove stale.
